name: Continuous Deployment to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t flask-backend:latest .

      - name: Deploy to EC2 using Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to the target directory
            cd chave-pen

            ssh -i "ch28102024.pem" ubuntu@10.0.2.37
            
            cd /fastlog-backend || git clone https://github.com/AgdaTaniguchi/fastlog-backend.git
            cd /fastlog-backend  # Make sure we are in the project directory

            # Pull the latest changes
            git pull origin main

            # Build Docker image
            docker build -t flask-backend:latest .

            # Deploy using Docker Swarm
            # docker service create --name backend --replicas 1 -p 80:80 flask-backend:latest
            docker run -d -p --name flask-backend 80:80 flask-backend:latest

            docker network connect fastlog flask-backend
          EOF
