name: Back-end CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test Flask Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Install pytest for testing

      - name: Build project (Optional, if needed)
        run: |
          source venv/bin/activate
          # For example, if you need to build something like a package, you can add build commands here.
          echo "Build step can be customized if necessary"
      
      - name: Start Flask app (Optional)
        run: |
          source venv/bin/activate
          FLASK_APP=server.py FLASK_ENV=development flask run &
          sleep 5  # Wait for the app to start
