name: Back-end CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test Python App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest  # or your preferred test command

      - name: Build project
        run: |
          source venv/bin/activate
          python setup.py sdist bdist_wheel  # Adjust according to your build process
