name: Continuous Deployment to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t flask-backend:latest .

      - name: Deploy to EC2 using Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd fastlog-backend

            # Pull the latest changes
            git pull origin main

            # Build Docker image
            docker build -t flask-backend:latest .

            docker stop flask-backend
            docker rm flask-backend

            docker network create --driver overlay fastlog || true

            # Deploy using Docker Swarm
            docker service create \
            --name flask-backend \
            --replicas 1 --env-file .env \
            -p 8501:8501 \
            --network fastlog \
            flask-backend:latest

          EOF
